name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths:
      - '**.cpp'
      - '**.h'
      - 'Makefile'
      - '.github/**'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      id: cache-gtest
      with:
        path: ./gtest
        key: ${{ runner.os }}-gtest
    - uses: actions/checkout@v2
    - name: build-gtest
      if: steps.cache-gtest.outputs.cache-hit != 'true'
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && mkdir ${GITHUB_WORKSPACE}/gtest && cp -r include lib  ${GITHUB_WORKSPACE}/gtest
      
    - name: make
      run: make all && ls
    - name: upload elf
      uses: actions/upload-artifact@v2
      with:
        name: dnsrrparser
        path: dnsrrparser
    - name: download elf
      uses: actions/download-artifact@v2
      with:
        name: dnsrrparser
        path: ~/download/path
    - name: Display structure of downloaded files
      run: bash -c "ls -R ~/download/path; pwd; cd ~/download/path; pwd; ls"
      working-directory: .
      
