name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths:
      - '**.cpp'
      - '**.h'
      - 'Makefile'
      - '.github/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all
    - name: bin_file    
      uses: actions/upload-artifact@v2
      with:
        name: dnsrrparser
        path: dnsrrparser
