name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths:
      - '**.cpp'
      - '**.h'
      - 'Makefile'
      - '.github/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all
    - name: upload elf
      uses: actions/upload-artifact@v2
      with:
        name: dnsrrparser
        path: dnsrrparser
    - name: download elf
      uses: actions/download-artifact@v2
      with:
        name: dnsrrparser
        path: ~/download/path
    - name: Display structure of downloaded files
      run: bash -c "ls -R ~/download/path; pwd; cd ~/downlad; pwd"
      working-directory: .
      
