name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all
    - name: bin_file    
      uses: actions/upload-artifact@v2
      with:
        name: dnsrrparser
        path: dnsrrparser
    - name: test_commit
      run: bash -c "if [ ! -f flag ];then touch flag; git config user.email 'den.ananas94@gmail.com'; git config user.name 'ananas94';  git add flag; git commit -m \"add flag\"; git push; else echo \"Hi\"; fi"

